
--- 수정 금지 ---
-- DROP TABLE
DROP TABLE REGISTRATION_USER CASCADE CONSTRAINTS;
DROP TABLE EXERCISE_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE EXERCISE CASCADE CONSTRAINTS;
DROP TABLE BOOKMARK CASCADE CONSTRAINTS;
DROP TABLE VOLUME CASCADE CONSTRAINTS;
DROP TABLE PROGRAM CASCADE CONSTRAINTS;
DROP TABLE RECORD CASCADE CONSTRAINTS;
DROP TABLE RECODE_EXERCISE_VOLUME CASCADE CONSTRAINTS;

-- DROP SEQUENCE
DROP SEQUENCE CATEGORY_SEQ;
DROP SEQUENCE EXERCISE_SEQ;
DROP SEQUENCE VOLUME_SEQ;
DROP SEQUENCE RECORD_SEQ;
---------------





--- 수정 가능 ---
----------- USER ------------
-- USER TABLE CREATE
CREATE TABLE REGISTRATION_USER (
	USER_ID VARCHAR2(30) PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	WEIGHT NUMBER,
	SEX VARCHAR2(2)
);

-- USER COMMNET
COMMENT ON COLUMN REGISTRATION_USER.USER_ID IS '사용자 ID';
COMMENT ON COLUMN REGISTRATION_USER.NAME IS '이름';
COMMENT ON COLUMN REGISTRATION_USER.WEIGHT IS '몸무게';
COMMENT ON COLUMN REGISTRATION_USER.SEX IS '성별';





----------- EXERCISE_CATEGORY ------------
-- EXERCISE_CATEGORY TABLE CREATE
CREATE TABLE EXERCISE_CATEGORY(
	C_NO VARCHAR2(10) PRIMARY KEY,
	C_NAME VARCHAR2(20) NOT NULL
);

-- EXERCISE_CATEGORY SEQUENCE
CREATE SEQUENCE CATEGORY_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- EXERCISE_CATEGORY COMMENT
COMMENT ON COLUMN EXERCISE_CATEGORY.C_NO IS '카테고리ID';
COMMENT ON COLUMN EXERCISE_CATEGORY.C_NAME IS '운동카테고리';

-- EXERCISE_CATEGORY INSERT
INSERT INTO EXERCISE_CATEGORY VALUES('C' || CATEGORY_SEQ.NEXTVAL, '하체');
INSERT INTO EXERCISE_CATEGORY VALUES('C' || CATEGORY_SEQ.NEXTVAL, '가슴');
INSERT INTO EXERCISE_CATEGORY VALUES('C' || CATEGORY_SEQ.NEXTVAL, '등');
INSERT INTO EXERCISE_CATEGORY VALUES('C' || CATEGORY_SEQ.NEXTVAL, '어깨');
INSERT INTO EXERCISE_CATEGORY VALUES('C' || CATEGORY_SEQ.NEXTVAL, '팔');
INSERT INTO EXERCISE_CATEGORY VALUES('C' || CATEGORY_SEQ.NEXTVAL, '복근');





----------- EXERCISE ------------
-- EXERCISE TABLE CREATE
CREATE TABLE EXERCISE(
	E_NO VARCHAR2(10) PRIMARY KEY,
	E_NAME VARCHAR2(20) NOT NULL,
	C_NO VARCHAR(20) NOT NULL REFERENCES EXERCISE_CATEGORY(C_NO),
	E_PHOTO VARCHAR2(100),
	E_CONTENT VARCHAR2(300) NOT NULL
);

-- EXERCISE SEQUENCE
CREATE SEQUENCE EXERCISE_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- EXERCISE COMMENT
COMMENT ON COLUMN EXERCISE.E_NO IS '운동ID';
COMMENT ON COLUMN EXERCISE.E_NAME IS '운동이름';
COMMENT ON COLUMN EXERCISE.C_NO IS 'CATEGORY ID';
COMMENT ON COLUMN EXERCISE.E_PHOTO IS '사진경로';
COMMENT ON COLUMN EXERCISE.E_CONTENT IS '운동설명';

-- EXERCISE INSERT
INSERT INTO EXERCISE VALUES('E' || EXERCISE_SEQ.NEXTVAL,'TEST1', 'C1', '/views/images/libimages/1.png', '하체');
INSERT INTO EXERCISE VALUES('E' || EXERCISE_SEQ.NEXTVAL,'TEST2', 'C2', '/views/images/libimages/1.png', '가슴');
INSERT INTO EXERCISE VALUES('E' || EXERCISE_SEQ.NEXTVAL,'TEST3', 'C3', '/views/images/libimages/1.png', '등');
INSERT INTO EXERCISE VALUES('E' || EXERCISE_SEQ.NEXTVAL,'TEST4', 'C4', '/views/images/libimages/1.png', '어깨');
INSERT INTO EXERCISE VALUES('E' || EXERCISE_SEQ.NEXTVAL,'TEST5', 'C5', '/views/images/libimages/1.png', '팔');
INSERT INTO EXERCISE VALUES('E' || EXERCISE_SEQ.NEXTVAL,'TEST6', 'C6', '/views/images/libimages/1.png', '복근');






----------- BOOKMARK ------------
-- BOOKMARK TABLE CTEATE
CREATE TABLE BOOKMARK (
	USER_ID VARCHAR2(30) NOT NULL REFERENCES REGISTRATION_USER(USER_ID) ,
	E_NO VARCHAR2(10) NOT NULL REFERENCES EXERCISE(E_NO)
);

-- BOOKMARK COMMENT
COMMENT ON COLUMN BOOKMARK.USER_ID IS '사용자 ID';
COMMENT ON COLUMN BOOKMARK.E_NO IS '북마크된 운동';





----------- PROGRAM ------------
--PROGRAM TABLE CTEATE
CREATE TABLE PROGRAM(
	P_NO NUMBER NOT NULL,
	E_NO VARCHAR2(10) NOT NULL,
	P_SET NUMBER NOT NULL,
	P_REPS NUMBER NOT NULL,
	P_KG NUMBER NOT NULL
);






----------- VOLUME ------------
-- VOLUME TABLE CTEATE
CREATE TABLE VOLUME(
	V_NO NUMBER PRIMARY KEY,
	V_REPS NUMBER,
	V_SET NUMBER,
	V_KG NUMBER,
	DO_CHECK NUMBER NOT NULL
);

-- VOLUME SEQUENCE
CREATE SEQUENCE VOLUME_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- VOLUME COMMNET
COMMENT ON COLUMN VOLUME.V_NO IS '볼륨ID';
COMMENT ON COLUMN VOLUME.V_REPS IS '운동 횟수';
COMMENT ON COLUMN VOLUME.V_SET IS '운동 세트 수';
COMMENT ON COLUMN VOLUME.V_KG IS '킬로그람';
COMMENT ON COLUMN VOLUME.DO_CHECK IS '운동 여부 체크';





----------- RECORD ------------
-- RECORD TABLE CTEATE
CREATE TABLE RECORD(
	R_NO NUMBER PRIMARY KEY,
	R_DATE VARCHAR2(20) NOT NULL,
	DO_CHECK NUMBER NOT NULL
);

-- RECORD SEQUENCE
CREATE SEQUENCE RECORD_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- RECORD COMMNET
COMMENT ON COLUMN RECORD.R_NO IS '운동기록 ID';
COMMENT ON COLUMN RECORD.R_DATE IS '기록 날짜';





----------- RECODE_EXERCISE_VOLUME ------------
-- RECODE_EXERCISE_VOLUME TABLE CTEATE
CREATE TABLE RECODE_EXERCISE_VOLUME(
	R_NO NUMBER NOT NULL REFERENCES RECORD(R_NO),
	E_NO VARCHAR2(20) NOT NULL REFERENCES EXERCISE(E_NO),
	V_NO NUMBER NOT NULL REFERENCES VOLUME(V_NO)
);

-- RECORD COMMNET
COMMENT ON COLUMN RECODE_EXERCISE_VOLUME.R_NO IS '운동기록 ID';
COMMENT ON COLUMN RECODE_EXERCISE_VOLUME.E_NO IS '기록된 운동 ID';
COMMENT ON COLUMN RECODE_EXERCISE_VOLUME.V_NO IS '기록된 운동 볼륨 ID';

